TONE_SWITCHER_PROMPTS = [
    "I have to do this task today.",
    "The meeting is scheduled for tomorrow morning.",
    "I am eating a sandwich right now.",
    "She walked to the store to buy milk.",
    "The weather is very cloudy today and it might rain.",
    "My computer crashed and I lost my work.",
    "I am going on a vacation next week.",
    "The cat is sleeping on the couch.",
    "I just finished reading a very long book.",
    "We need to clean the house before guests arrive.",
    "The train arrives at 8 AM.",
    "I am looking out the window.",
    "He forgot his keys on the table.",
    "The alarm clock is ringing loudly.",
    "I need to call my manager.",
    "She is painting a picture.",
    "The car ran out of gas on the highway.",
    "We are having pasta for dinner.",
    "The movie is starting in five minutes.",
    "I lost my wallet at the park.",
    "He is fixing the broken chair.",
    "The flowers are blooming in the garden.",
    "I am waiting for the bus.",
    "She received a package in the mail.",
    "We have to submit the project by Friday.",
    "The dog chased the ball into the street.",
    "I am drinking a cup of coffee.",
    "He spilled water all over the floor.",
    "The sun is setting behind the mountains.",
    "I need to buy groceries tonight."
]

WORD_CHOICE_PROMPTS = [
    "happy", "sad", "fast", "slow", "smart", "angry", "brave", "tired", "beautiful", "scary", "loud", "quiet", "strong", "weak", "funny",
    "cold", "hot", "big", "small", "dark", "light", "heavy", "light", "hard", "soft", "rich", "poor", "clean", "dirty", "easy",
    "difficult", "good", "bad", "right", "wrong", "true", "false", "safe", "dangerous", "early", "late", "near", "far", "high", "low",
    "old", "young", "new", "full", "empty", "open", "closed", "wet", "dry", "sweet", "sour", "rough", "smooth", "sharp", "dull",
    "bright", "dim", "thick", "thin", "wide", "narrow", "deep", "shallow", "busy", "lazy", "courageous", "cowardly", "generous", "selfish", "polite"
]

REDUNDANCY_PROMPTS = [
    ("I want to repeat again.", "I want to repeat."),
    ("They arrived at 12 midnight.", "They arrived at midnight."),
    ("The end result was surprising.", "The result was surprising."),
    ("He nodded his head in agreement.", "He nodded in agreement."),
    ("She entered into the room.", "She entered the room."),
    ("It is absolutely essential to go.", "It is essential to go."),
    ("They collaborated together on the project.", "They collaborated on the project."),
    ("I need to rethink my past history.", "I need to rethink my history."),
    ("The actual fact is that it works.", "The fact is that it works."),
    ("He gave a free gift to his friend.", "He gave a gift to his friend."),
    ("We need basic fundamentals to succeed.", "We need fundamentals to succeed."),
    ("She made an unexpected surprise appearance.", "She made a surprise appearance."),
    ("The new innovation changed the industry.", "The innovation changed the industry."),
    ("He added a bonus extra feature.", "He added a bonus feature."),
    ("They gathered together in the hall.", "They gathered in the hall."),
    ("It was a sudden crisis that happened quickly.", "It was a sudden crisis."),
    ("The two twins look alike.", "The twins look alike."),
    ("I need to reply back to her email.", "I need to reply to her email."),
    ("The end conclusion was obvious.", "The conclusion was obvious."),
    ("He reverted back to his old ways.", "He reverted to his old ways."),
    ("We must plan ahead for the trip.", "We must plan for the trip."),
    ("She was totally completely exhausted.", "She was completely exhausted."),
    ("The true facts were revealed.", "The facts were revealed."),
    ("He knelt down on the floor.", "He knelt on the floor."),
    ("The regular routine is boring.", "The routine is boring."),
    ("We are surrounded on all sides.", "We are surrounded."),
    ("She postponed it until later.", "She postponed it."),
    ("The empty void was scary.", "The void was scary."),
    ("We reached a mutual agreement.", "We reached an agreement."),
    ("The ATM machine is out of order.", "The ATM is out of order.")
]

SENTENCE_BUILDER_PROMPTS = [
    {"words": ["dog", "the", "barking", "is", "loudly"], "target": "the dog is barking loudly."},
    {"words": ["jumps", "fox", "brown", "quick", "the"], "target": "the quick brown fox jumps."},
    {"words": ["coding", "she", "night", "all", "loves"], "target": "she loves coding all night."},
    {"words": ["apple", "ate", "an", "yesterday", "he"], "target": "he ate an apple yesterday."},
    {"words": ["brightly", "sky", "the", "in", "shines", "sun", "the"], "target": "the sun shines brightly in the sky."},
    {"words": ["cat", "mat", "sat", "the", "on", "the"], "target": "the cat sat on the mat."},
    {"words": ["fast", "very", "runs", "cheetah", "the"], "target": "the cheetah runs very fast."},
    {"words": ["book", "reading", "am", "i", "good", "a"], "target": "i am reading a good book."},
    {"words": ["cake", "baking", "is", "delicious", "a", "she"], "target": "she is baking a delicious cake."},
    {"words": ["park", "to", "went", "we", "the"], "target": "we went to the park."},
    {"words": ["car", "blue", "drives", "a", "he"], "target": "he drives a blue car."},
    {"words": ["pizza", "eating", "are", "they", "cheese"], "target": "they are eating cheese pizza."},
    {"words": ["song", "beautiful", "sang", "a", "bird", "the"], "target": "the bird sang a beautiful song."},
    {"words": ["code", "writing", "enjoy", "i", "python"], "target": "i enjoy writing python code."},
    {"words": ["mountain", "high", "climbed", "the", "hikers", "the"], "target": "the hikers climbed the high mountain."},
    {"words": ["cold", "water", "drank", "the", "girl", "the"], "target": "the girl drank the cold water."},
    {"words": ["slowly", "walked", "old", "man", "the"], "target": "the old man walked slowly."},
    {"words": ["funny", "joke", "laughed", "at", "the", "we"], "target": "we laughed at the funny joke."},
    {"words": ["new", "shoes", "bought", "pair", "a", "of", "she"], "target": "she bought a new pair of shoes."},
    {"words": ["quickly", "homework", "finished", "his", "he"], "target": "he finished his homework quickly."},
    {"words": ["tree", "tall", "climbed", "the", "monkey", "the"], "target": "the monkey climbed the tall tree."},
    {"words": ["sweet", "tasted", "apple", "red", "the"], "target": "the red apple tasted sweet."},
    {"words": ["loud", "music", "played", "the", "band", "the"], "target": "the band played the loud music."},
    {"words": ["beautifully", "painted", "picture", "the", "artist", "the"], "target": "the artist painted the picture beautifully."},
    {"words": ["fast", "drove", "car", "sports", "the", "he"], "target": "he drove the sports car fast."},
    {"words": ["quietly", "slept", "baby", "the", "room", "in", "the"], "target": "the baby slept quietly in the room."},
    {"words": ["hard", "studied", "test", "for", "the", "she"], "target": "she studied hard for the test."},
    {"words": ["long", "letter", "wrote", "a", "friend", "his", "to", "he"], "target": "he wrote a long letter to his friend."},
    {"words": ["delicious", "meal", "cooked", "the", "chef", "the"], "target": "the chef cooked the delicious meal."},
    {"words": ["sky", "blue", "flew", "the", "in", "birds", "the"], "target": "the birds flew in the blue sky."}
]

SENTENCE_RECONSTRUCTOR_PROMPTS = [
    {"original": "Yo, the meeting is gonna start soon so get in here.", "tone": "formal"},
    {"original": "Send me that file whenever you get a sec.", "tone": "formal"},
    {"original": "I ain't gonna do that work today, it's too hard.", "tone": "formal"},
    {"original": "We need to fix this bug super fast.", "tone": "formal"},
    {"original": "My bad for missing the call yesterday.", "tone": "formal"},
    {"original": "Gimmee the report ASAP.", "tone": "formal"},
    {"original": "Yeah, I'm down to help out with that thing.", "tone": "formal"},
    {"original": "Hit me up when you finish the task.", "tone": "formal"},
    {"original": "I totally blanked on sending that email.", "tone": "formal"},
    {"original": "Let's touch base later today to chat.", "tone": "formal"},
    {"original": "That idea is totally whacked out.", "tone": "professional"},
    {"original": "I am so done with this project, it's driving me nuts.", "tone": "professional"},
    {"original": "The boss was pretty mad about the delay.", "tone": "diplomatic"},
    {"original": "You messed up the presentation big time.", "tone": "constructive"},
    {"original": "I don't wanna go to the team lunch today.", "tone": "polite"},
    {"original": "Hurry up and finish your part of the code.", "tone": "collaborative"},
    {"original": "Why didn't you reply to my message?", "tone": "professional inquiring"},
    {"original": "This design sucks.", "tone": "constructive criticism"},
    {"original": "I'm not doing that, it's not my job.", "tone": "professional boundary setting"},
    {"original": "We gotta tell the client the bad news.", "tone": "professional reporting"}
]

PLOT_HOLE_PROMPTS = [
    ("Rahul went to Delhi. Rahul in Mumbai was walking.", "There is a contradiction because he didn't travel."),
    ("The door was locked from the outside. He walked out and closed it.", "He cannot lock it from the outside without exiting first."),
    ("She was allergic to peanuts. She enjoyed her peanut butter sandwich.", "She cannot enjoy a peanut butter sandwich if she is allergic."),
    ("It was pitch black outside at noon.", "It shouldn't be pitch black at noon unless there's an eclipse."),
    ("He drowned in the desert sand.", "You cannot drown in sand, only suffocate or sink."),
    ("The medieval knight fired his laser blaster.", "A medieval knight would not have a laser blaster."),
    ("The deaf man heard her whispered warning.", "A deaf man cannot hear a whispered warning."),
    ("They drove their car across the ocean to Europe.", "You cannot drive a car across an ocean."),
    ("The vampire walked out into the bright noon sun without issues.", "Vampires are traditionally harmed by sunlight."),
    ("He read the closed book in absolute darkness.", "You cannot read a closed book, nor read in absolute darkness."),
    ("The ghost picked up the heavy iron sword and swung it.", "Ghosts are usually portrayed as incorporeal and cannot pick up heavy objects."),
    ("The spaceship accelerated to faster-than-light speeds using a diesel engine.", "A diesel engine cannot power FTL travel."),
    ("She texted him from her smartphone in the year 1850.", "Smartphones did not exist in 1850."),
    ("The fish held its breath underwater for an hour.", "Fish breathe underwater using gills, they don't hold their breath."),
    ("He froze the water by holding it over the blazing fire.", "Fire heats water; it does not freeze it."),
    ("The blind archer easily hit the bullseye at 200 yards in the dark.", "A blind person cannot see the target, darkness makes it harder even for a sighted person."),
    ("The T-Rex flew gracefully through the clouds.", "T-Rexes did not have wings and could not fly."),
    ("She whispered across the noisy, crowded rock concert perfectly clearly.", "A whisper cannot be heard over a loud rock concert."),
    ("He fell upwards into the clear blue sky.", "Gravity pulls things downwards, not upwards."),
    ("The ice cub melted completely in the freezer.", "Ice does not melt in a freezer unless it's broken.")
]
